Repository owncloud/password_policy, pull requests merged in 2018-07, with the labels that each got.

#31 Do not allow passwords to be expired for non-local users
  lib/Command/ExpirePassword.php
  tests/Command/ExpirePasswordTest.php
Labels: 3 - To Review, bug

#36 Check password type based on event name + allow empty password for public links
  appinfo/app.php
  lib/Engine.php
  lib/HooksHandler.php
  tests/EngineTest.php
  tests/HooksHandlerTest.php
Labels: 3 - To Review, p2-high

#34 Create a new entry in user_password_history when a new user is created
  appinfo/app.php
  lib/HooksHandler.php
  tests/HooksHandlerTest.php
Labels: 3 - To Review

#27 send notification when passwords are about to expire
  appinfo/app.php
  appinfo/info.xml
  js/notification.js
  lib/AppInfo/Application.php
  lib/Controller/PasswordController.php
  lib/Controller/SettingsController.php
  lib/Db/OldPasswordMapper.php
  lib/HooksHandler.php
  lib/Jobs/PasswordExpirationNotifierJob.php
  lib/Notifier.php
  lib/Rules/PasswordHistory.php
  lib/UserNotificationConfigHandler.php
  templates/admin.php
  templates/password.php
  tests/Controller/PasswordControllerTest.php
  tests/Db/OldPasswordMapperTest.php
  tests/HooksHandlerTest.php
  tests/Jobs/PasswordExpirationNotifierJobTest.php
  tests/NotifierTest.php
  tests/Rules/PasswordHistoryTest.php
  tests/UserNotificationConfigHandlerTest.php
Labels: 3 - To Review

#44 Update changelog for v2.0.0
  CHANGELOG.md
Labels: 3 - To Review

#51 Send an expired notification when the admin expires a password
  lib/Command/ExpirePassword.php
  lib/Db/OldPassword.php
  lib/Db/OldPasswordMapper.php
  lib/Jobs/PasswordExpirationNotifierJob.php
  lib/Rules/PasswordExpired.php
  lib/Rules/PasswordHistory.php
  tests/Command/ExpirePasswordTest.php
  tests/Db/OldPasswordMapperTest.php
  tests/Jobs/PasswordExpirationNotifierJobTest.php
  tests/Rules/PasswordExpiredTest.php
Labels: 3 - To Review

#56 Check the user exists before sending the notification
  lib/Jobs/PasswordExpirationNotifierJob.php
  tests/Jobs/PasswordExpirationNotifierJobTest.php
Labels: 3 - To Review

#62 Return a constant if the user cannot change their password
  lib/Command/ExpirePassword.php
  tests/Command/ExpirePasswordTest.php
Labels: 3 - To Review, enhancement, p4-low, technical debt

#60 Return a constant not a magic number if the user is null
  lib/Command/ExpirePassword.php
  tests/Command/ExpirePasswordTest.php
Labels: enhancement, p4-low, technical debt
