Repository owncloud/password_policy, pull requests merged in 2018-08, with the labels that each got.

#82 Remove strip_tags to include tags as special chars
  lib/Controller/SettingsController.php
Labels: 3 - To Review

#77 Add options 'all' and 'group' to expire-password command
  lib/Command/ExpirePassword.php
  tests/Command/ExpirePasswordTest.php
Labels: 3 - To Review

#81 Update the messages for first time login
  lib/Controller/PasswordController.php
  lib/HooksHandler.php
  templates/password.php
  tests/Controller/PasswordControllerTest.php
  tests/HooksHandlerTest.php
Labels: 3 - To Review, Effort: 0.25d

#83 Clean up tables after user deletion
  appinfo/app.php
  lib/Db/OldPasswordMapper.php
  lib/HooksHandler.php
  tests/Db/OldPasswordMapperTest.php
  tests/HooksHandlerTest.php
Labels: 3 - To Review

#86 Update changelog for upcoming version
  CHANGELOG.md
Labels: 3 - To Review

#79 Add symfony events for about to expire and expired
  lib/Jobs/PasswordExpirationNotifierJob.php
  tests/Jobs/PasswordExpirationNotifierJobTest.php
Labels: 3 - To Review, Effort: trivial

#91 Move unit tests into tests/unit folder
  .gitignore
  tests/travis/unit.sh
  tests/unit/Command/ExpirePasswordTest.php
  tests/unit/Controller/PasswordControllerTest.php
  tests/unit/Db/OldPasswordMapperTest.php
  tests/unit/EngineTest.php
  tests/unit/HooksHandlerTest.php
  tests/unit/Jobs/PasswordExpirationNotifierJobTest.php
  tests/unit/NotifierTest.php
  tests/unit/Rules/LengthTest.php
  tests/unit/Rules/LowercaseTest.php
  tests/unit/Rules/NumbersTest.php
  tests/unit/Rules/PasswordExpiredTest.php
  tests/unit/Rules/PasswordHistoryTest.php
  tests/unit/Rules/SpecialTest.php
  tests/unit/Rules/UppercaseTest.php
  tests/unit/UserNotificationConfigHandlerTest.php
  tests/unit/bootstrap.php
  tests/unit/phpunit.xml
Labels: 3 - To Review

#92 Remember errors in lint of PHP files
  lib/Controller/SettingsController.php
  tests/travis/lint.sh
Labels: 3 - To Review

#90 Add testing to Makefile
  .gitignore
  .php_cs.dist
  Makefile
  composer.json
  composer.lock
  lib/Controller/SettingsController.php
  vendor-bin/owncloud-codestyle/composer.json
Labels: 3 - To Review

#99 Find codestyle dependencies that fit with PHP 5.6
  composer.json
  composer.lock
  vendor-bin/owncloud-codestyle/composer.json
Labels: 3 - To Review

#102 Do not rely on sorted list from getPasswordsAboutToExpire()
  tests/unit/Db/OldPasswordMapperTest.php
Labels: 3 - To Review

#98 PHP style and PHP unit on drone
  .drone.yml
Labels: 3 - To Review

#106 Add drone build status badge
  README.md
Labels: 3 - To Review

#108 First web ui acceptance tests
  .drone.yml
  .gitignore
  tests/acceptance/config/behat.yml
  tests/acceptance/features/bootstrap/PasswordPolicyContext.php
  tests/acceptance/features/bootstrap/WebUIPasswordPolicyContext.php
  tests/acceptance/features/bootstrap/bootstrap.php
  tests/acceptance/features/lib/PasswordPolicySettingsPage.php
  tests/acceptance/features/webUIPasswordPolicy/passwordRequirementSettings.feature
Labels: 3 - To Review, dev:acceptance-tests

#111 Test steps to check underlying policy settings
  tests/acceptance/features/bootstrap/PasswordPolicyContext.php
  tests/acceptance/features/webUIPasswordPolicy/passwordRequirementSettings.feature
Labels: 3 - To Review, QA-team, dev:acceptance-tests

#112 remove excess code in .drone.yml
  .drone.yml
Labels: 3 - To Review, QA-team, dev:acceptance-tests

#114 Fix OldPasswordMapper for Oracle
  .drone.yml
  lib/Db/OldPasswordMapper.php
Labels: 3 - To Review

#116 webUI tests for disabling password policies
  tests/acceptance/features/bootstrap/PasswordPolicyContext.php
  tests/acceptance/features/webUIPasswordPolicy/disablePolicySettings.feature
  tests/acceptance/features/webUIPasswordPolicy/enablePolicySettings.feature
Labels: 3 - To Review, QA-team, dev:acceptance-tests

#117 Tests for setting password policy values on the webUI
  tests/acceptance/features/bootstrap/PasswordPolicyContext.php
  tests/acceptance/features/bootstrap/WebUIPasswordPolicyContext.php
  tests/acceptance/features/lib/PasswordPolicySettingsPage.php
  tests/acceptance/features/webUIPasswordPolicy/setPolicySettings.feature
Labels: 3 - To Review, QA-team, dev:acceptance-tests

#118 add PHP 7.2 for unit tests
  .drone.yml
Labels: 3 - To Review, QA-team

#115 Disable occ user:expire-password if no expiration rule was configured
  lib/Command/ExpirePassword.php
  tests/unit/Command/ExpirePasswordTest.php
Labels: 3 - To Review
