Repository owncloud/password_policy, pull requests merged in 2019-12, with the labels that each got.

#270 change 10.0 to latest in doc link
  appinfo/info.xml
Labels: 3 - To Review

#271 Adjust tests
  .drone.starlark
  .drone.yml
  composer.json
  composer.lock
  phpunit.xml
  tests/unit/Command/ExpirePasswordTest.php
  tests/unit/Controller/PasswordControllerTest.php
  tests/unit/Db/OldPasswordMapperTest.php
  tests/unit/EngineTest.php
  tests/unit/HooksHandlerTest.php
  tests/unit/Jobs/PasswordExpirationNotifierJobTest.php
  tests/unit/NotifierTest.php
  tests/unit/Rules/LengthTest.php
  tests/unit/Rules/LowercaseTest.php
  tests/unit/Rules/NumbersTest.php
  tests/unit/Rules/PasswordExpiredTest.php
  tests/unit/Rules/PasswordHistoryTest.php
  tests/unit/Rules/SpecialTest.php
  tests/unit/Rules/UppercaseTest.php
  tests/unit/UserNotificationConfigHandlerTest.php
  vendor-bin/behat/composer.json
Labels: 3 - To Review, QA-team

#272 Add sabre/xml to behat dependencies
  .drone.starlark
  .drone.yml
  vendor-bin/behat/composer.json
Labels: 3 - To Review, QA-team, dev:acceptance-tests

#273 Coding standard 2.0.0
  .drone.starlark
  tests/unit/Controller/PasswordControllerTest.php
  tests/unit/EngineTest.php
  tests/unit/HooksHandlerTest.php
  tests/unit/NotifierTest.php
  tests/unit/Rules/LengthTest.php
  tests/unit/Rules/LowercaseTest.php
  tests/unit/Rules/NumbersTest.php
  tests/unit/Rules/PasswordExpiredTest.php
  tests/unit/Rules/PasswordHistoryTest.php
  tests/unit/Rules/SpecialTest.php
  tests/unit/Rules/UppercaseTest.php
  vendor-bin/owncloud-codestyle/composer.json
Labels: 3 - To Review, QA-team

#268 Merge Back Release 2.1.0
  CHANGELOG.md
  appinfo/info.xml
Labels: 2 - Developing
