Repository owncloud/password_policy, pull requests merged in 2020-06, with the labels that each got.

#307 [Tests-Only] Refactor acceptance tests in passwordpolicy app
  tests/acceptance/features/webUIPasswordReset/passwordResetLastPasswords.feature
  tests/acceptance/features/webUIPasswordReset/passwordResetLowercaseLetters.feature
  tests/acceptance/features/webUIPasswordReset/passwordResetMinimumLength.feature
  tests/acceptance/features/webUIPasswordReset/passwordResetNumbers.feature
  tests/acceptance/features/webUIPasswordReset/passwordResetRequirementCombinations.feature
  tests/acceptance/features/webUIPasswordReset/passwordResetSpecialCharacters.feature
  tests/acceptance/features/webUIPasswordReset/passwordResetSpecialCharactersRestriction.feature
  tests/acceptance/features/webUIPasswordReset/passwordResetUppercaseLetters.feature
  tests/acceptance/features/webUIPublicShareLink/publicShareLinkExpirationPolicyEdgeCases.feature
Labels: 4 - To release, QA-team

#308 Updating bamarni/composer-bin-plugin (1.4.0 => 1.4.1)
  composer.lock
Labels: 3 - To Review

#309 Adjust phpstan.neon for new bootstrapFiles setting
  lib/Jobs/PasswordExpirationNotifierJob.php
  phpstan.neon
Labels: 3 - To Review, QA-team

#311 Remove phpstan ignores fixed in phpstan 0.12.29
  lib/Jobs/PasswordExpirationNotifierJob.php
Labels: QA-team
