Repository owncloud/password_policy, pull requests merged in 2020-02, with the labels that each got.

#275 check first time password change necessary in postLogin
  lib/HooksHandler.php
  tests/unit/HooksHandlerTest.php
Labels: 3 - To Review

#279 Adjust Symfony eventDispatcher->dispatch calls
  .drone.starlark
  .drone.yml
  lib/HooksHandler.php
  lib/Jobs/PasswordExpirationNotifierJob.php
  tests/unit/Jobs/PasswordExpirationNotifierJobTest.php
Labels: 4 - To release

#281 Update starlark code 20200208
  .drone.star
  .drone.yml
Labels: 4 - To release, Drone, QA-team

#282 Update guzzle for testing to 6.5
  vendor-bin/behat/composer.json
Labels: QA-team, dev:acceptance-tests
