Repository owncloud/password_policy, pull requests merged in 2020-04, with the labels that each got.

#297 [Tests-Only] Update phpstan to latest version
  .drone.star
  lib/Command/ExpirePassword.php
  lib/Controller/PasswordController.php
  lib/Db/OldPasswordMapper.php
  lib/Engine.php
  lib/Jobs/PasswordExpirationNotifierJob.php
  lib/Rules/PasswordExpired.php
  phpstan.neon
  vendor-bin/phpstan/composer.json
Labels: 4 - To release, QA-team

#298 Drop PHP 7.1
  .drone.star
  composer.json
  composer.lock
Labels: 3 - To Review, QA-team

#300 [Tests-Only] Bump phan 2.7
  vendor-bin/phan/composer.json
Labels: QA-team

#301 Implement phpunit v8
  tests/unit/Command/ExpirePasswordTest.php
  vendor-bin/behat/composer.json
Labels: 3 - To Review, QA-team

#303 Adjust drone pipelines for PHP 7.4
  .drone.star
  .gitignore
Labels: 3 - To Review, QA-team
